[project]
name = "firmware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "esptool>=5.1.0",
    "intelhex>=2.3.0",
    "platformio>=6.1.19",
]
